TALight evaluation manager service called for problem:
   conio1
Universal Random Seed for this call to the service: 449701.

File ../../common/README_synopsis.typ downloaded in the output folder.
File ../../common/README_rtal.typ downloaded in the output folder.
File README_this_TALight_problem.typ not found!
The server is running in TRACKING mode, that is, it keeps track of the autenticated submissions and their evaluation results.
And the user has autenticated by providing his personal token in this call to the server.

Trying to read the data.yaml file `/home/ubuntu/esami-algo-private/esercitazioni_homeworks_algo_2024/conio1/testo/data.yaml` ...
Ok: data.yaml file successfully read and parsed.
The testbed has been successfully created.

Subtask 1 (4 testcases):

Case #001 [esempi_testo - hardcoded]: has been sent to you. Meanwhile you begin receiving it we start the chron.

Case #002 [esempi_testo - hardcoded]: has been sent to you. Meanwhile you begin receiving it we start the chron.

Case #003 [esempi_testo - hardcoded]: has been sent to you. Meanwhile you begin receiving it we start the chron.

Case #004 [esempi_testo - hardcoded]: has been sent to you. Meanwhile you begin receiving it we start the chron.

Trying to store the results of the evalution in the database on the server.
-Ok. The results of the evalution have been stored in the database on the server.

File result.txt downloaded in your output folder.

Bye-bye, my logging service ends here. Hope to see you again.
